export const Terrain = {
    Void: 9,
    Transparent: 29,
    DoorOpen: 10,
    DoorOpened: 21,
    DoorLocked: 11,
    Stair: 22,
    Button: 25,
    ButtonPushed: 24,
    CornerSE:8,
    CornerNW:0,
    CornerNE:2,
    CornerSW:6,
    WallN: 1,
    WallS: 7,
    WallE: 5,
    WallW: 3,
    Floor: 4,
    FloorAlt1: 18,
    FloorAlt2: 19,
    FloorAlt3: 20,
    Deco: 1000,
    Deco1: 12,
    Deco2: 13,
    Deco3: 14,
    Deco4: [15,16],
    Deco5: 17,
    Torch: 26,
    VegetalWall: 27,
    VegetalFloor: 28,
    CarpetNW: 30,
    CarpetN: 31,
    CarpetNE: 32,
    CarpetW:  33,
    Carpet: 34,
    CarpetE:  35,
    CarpetSW:  36,
    CarpetS:  37,
    CarpetSE:  38,
    SwordDeco:  39,
    PiedestalNW: 40,
    PiedestalN: 41,
    PiedestalNE: 42,
    PiedestalW:  43,
    Piedestal: 44,
    PiedestalE:  45,
    PiedestalSW:  46,
    PiedestalS:  47,
    PiedestalSE:  48,
    WallRift: 49,
    WaterFloor:  50,
    WaterWall:  51,
    Archer: 52,
};
export const GreeceCreationParams = {
    Area: 250, // min area of a room
    Fuzz: 0.25, // room size variation +-
    MinClusterSize: 5, // minimal cluster of room
    Width: 60,
    Height: 40,
    MinSubSize: 6, // subdivise into subcluster if cluster is bigger than MinSubSize
    canvasWidth: 100,
    canvasHeight: 100,
    Algo: 'rogue',
    Locks: false,
    Danger: [50, 70, 70, 80],
    Loots: [10, 6, 4, 4],
    LastLevel: false,
};